name: DevSecOps CI Auditoria
on: [push] # S'activa amb cada push

jobs:
  test-security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install selenium
    - name: Run Security Tests
      env:
        SECRET_KEY: ${{ secrets.MY_SECRET_KEY }} # Secret de GitHub
        MOZ_HEADLESS: 1
      run: python manage.py test core.tests_selenium -v 2
